version: "2.1"

services:
  main:
    image: nginxproxy/nginx-proxy:1.0.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./htpasswd:/etc/nginx/htpasswd
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy
    restart: unless-stopped

  letsencrypt:
    image: nginxproxy/acme-companion:2.2.1
    environment:
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - main
    networks:
      - nginx-proxy
    restart: unless-stopped

volumes:
  certs:
  vhost:
  html:
  acme:

networks:
  nginx-proxy:
    name: nginx-proxy
